### PR TITLE
Add Vazir font

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add font for Arabic script languages (Arabic / Persian)
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | -
| Possible impacts? | Fonts created by `tcpdf/tools/tcpdf_addfont.php`. Doesn't impact TCPDF, will be used by `PS/classes/pdf/PDFGenerator.php`

Screenshot from 2022-05-01 11-37-29

### CODE REVIEW

**Comment by mparvazi** [comment]
Screenshot from 2022-05-01 11-52-53

**Comment by matks** [comment]
Hi @mparvazi we created this repository as a fork of https://github.com/tecnickcom/TCPDF because we are waiting for a [contribution of ours](https://github.com/tecnickcom/TCPDF/pull/510) to be merged into https://github.com/tecnickcom/TCPDF .

But this fork is temporary, as soon as https://github.com/tecnickcom/TCPDF/pull/510 is merged we'll stop using it. It's better to rely on the official repository and not our fork.

We created this fork because we want to start having php8.1 compatibility although TCPDF is not ready yet. However I think we wish to not differ too much between our fork and the original repository ;)

**Comment by matks** [comment]
The best would be that you contribute to https://github.com/tecnickcom/TCPDF and not our fork ;) this will benefit prestashop community _and_ tcpdf users

**Comment by mparvazi** [comment]
> The best would be that you contribute to https://github.com/tecnickcom/TCPDF and not our fork ;) this will benefit prestashop community _and_ tcpdf users

OK. I'll make a PR there.

**Pull request closed without merging**
